// Code generated by MockGen. DO NOT EDIT.
// Source: myinterface/myinterface.go

// Package mock_myinterface is a generated GoMock package.
package mock_myinterface

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMyInterface is a mock of MyInterface interface.
type MockMyInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMyInterfaceMockRecorder
}

// MockMyInterfaceMockRecorder is the mock recorder for MockMyInterface.
type MockMyInterfaceMockRecorder struct {
	mock *MockMyInterface
}

// NewMockMyInterface creates a new mock instance.
func NewMockMyInterface(ctrl *gomock.Controller) *MockMyInterface {
	mock := &MockMyInterface{ctrl: ctrl}
	mock.recorder = &MockMyInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMyInterface) EXPECT() *MockMyInterfaceMockRecorder {
	return m.recorder
}

// IsUnder16 mocks base method.
func (m *MockMyInterface) IsUnder16(i int) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUnder16", i)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUnder16 indicates an expected call of IsUnder16.
func (mr *MockMyInterfaceMockRecorder) IsUnder16(i interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUnder16", reflect.TypeOf((*MockMyInterface)(nil).IsUnder16), i)
}
